import { getTime, parseISO } from 'date-fns';
import type { IpcCommandMap } from '@/lib/types/ipc';

export const sidebarAccounts = [
  {
    id: 'account-1',
    email: 'alex@example.com',
    displayName: 'Alex Morgan',
    avatarUrl: null,
    needsReauthentication: false,
  },
  {
    id: 'account-2',
    email: 'reauth@example.com',
    displayName: 'Reauth Account',
    avatarUrl: null,
    needsReauthentication: true,
  },
] satisfies IpcCommandMap['list_accounts']['result'];

export const sidebarMailboxes = [
  { id: 'INBOX', name: 'Inbox', unreadCount: 3 },
  { id: 'STARRED', name: 'Starred', unreadCount: 0 },
  { id: 'DRAFT', name: 'Drafts', unreadCount: 1 },
  { id: 'SENT', name: 'Sent', unreadCount: 0 },
  { id: 'SPAM', name: 'Spam', unreadCount: 0 },
  { id: 'TRASH', name: 'Trash', unreadCount: 0 },
];

export const ipcFixtures: { [C in keyof IpcCommandMap]: IpcCommandMap[C]['result'] } = {
  health_check: { status: 'ok' },
  open_external_url: undefined,
  write_frontend_log: undefined,
  read_settings: {
    theme: 'system',
    layout: 'three-column',
    density: 'comfortable',
    sidebarCollapsed: false,
    sidebarWidth: 260,
    listWidth: 350,
    readerHeight: 40,
    syncOnStartup: true,
    showUnreadCounts: true,
    syncIntervalSeconds: 300,
    showSenderAvatars: true,
    zoomPercent: 100,
    alwaysLoadRemoteImages: false,
    allowedImageSenders: [],
    commandOverrides: {},
    logLevel: 'info',
    prefetchImageAttachments: false,
    startAtLogin: false,
    closeToTray: true,
    startMinimized: false,
    desktopNotifications: true,
    updateCheckInterval: '1d',
    installUpdateOnQuit: true,
  },
  write_setting: undefined,
  read_log_entries: [
    {
      timestampMillis: getTime(parseISO('2026-08-19T09:41:22.118Z')),
      level: 'ERROR',
      message: 'sync: history sync failed for alex@example.com',
    },
    {
      timestampMillis: getTime(parseISO('2026-08-19T09:40:58.702Z')),
      level: 'INFO',
      message: 'queue: mutation lane seated mutation:star:17f3a2c9',
    },
    {
      timestampMillis: getTime(parseISO('2026-08-19T09:38:11.365Z')),
      level: 'ERROR',
      message:
        'frontend: load_conversation failed: database is locked\n    at dispatchInvoke (commands.ts:14:11)',
    },
  ],
  pause_queue: { pending: 0, active: 0, failed: 0, done: 0, paused: true, suspended: false },
  resume_queue: { pending: 0, active: 0, failed: 0, done: 0, paused: false, suspended: false },
  read_queue_summary: {
    pending: 0,
    active: 0,
    failed: 0,
    done: 0,
    paused: false,
    suspended: false,
  },
  list_accounts: [],
  begin_sign_in: undefined,
  begin_reauthentication: undefined,
  remove_account: undefined,
  list_labels: [],
  lookup_contacts: [],
  reply_context: {
    to: [],
    cc: [],
    subject: '',
    originalMessageId: '',
    targetThreadId: null,
    inReplyTo: null,
    references: [],
    originalGmailMessageId: '',
    displayQuote: null,
    attachments: [],
  },
  stage_attachment_from_path: {
    id: '',
    filename: '',
    mimeType: '',
    path: '',
    contentId: null,
    size: 0,
  },
  stage_attachment_from_bytes: {
    id: '',
    filename: '',
    mimeType: '',
    path: '',
    contentId: null,
    size: 0,
  },
  release_staged_attachment: undefined,
  stage_attachment_into_draft: {
    id: '',
    filename: '',
    mimeType: '',
    path: '',
    contentId: null,
    size: 0,
  },
  save_compose_draft: { operationId: 'draft-operation', draftId: 'draft-1' },
  send_compose_draft: { operationId: 'send-operation', draftId: 'draft-1' },
  discard_compose_draft: undefined,
  hydrate_compose_draft: {
    sessionId: 'session-1',
    accountId: 'account-1',
    draftId: 'draft-1',
    from: 'alex@example.com',
    to: [],
    cc: [],
    bcc: [],
    subject: '',
    html: '',
    quoteHtml: null,
    quotePlain: null,
    mode: 'draft',
    threadId: null,
    inReplyTo: null,
    references: [],
    originalMessageId: null,
    originalGmailMessageId: null,
    attachments: [],
  },
  'plugin:dialog|open': null,
  'plugin:dialog|save': null,
  ensure_attachment_cached: {
    cachePath: '',
    displayPath: '',
    mimeType: '',
    filename: '',
    size: 0,
  },
  read_attachment_bytes: new ArrayBuffer(0),
  read_attachment_text: '',
  save_attachment_to_path: undefined,
  list_threads: { items: [], nextCursor: null, previousCursor: null },
  load_conversation: { threadId: '', subject: '', messages: [] },
  load_message_body: {
    htmlBody: null,
    plainBody: null,
    htmlPresence: 'absent',
    truncated: false,
    remoteImagesBlocked: false,
    remoteImagesAllowed: false,
    inlineImagesPending: false,
  },
  fetch_message_body: undefined,
  trigger_sync: { accountId: '', state: 'idle', lastSyncedAt: null, lastError: null },
  read_sync_status: { accountId: '', state: 'idle', lastSyncedAt: null, lastError: null },
  star_thread: undefined,
  unstar_thread: undefined,
  mark_thread_read: undefined,
  mark_thread_unread: undefined,
  mutate_threads: [],
  mutate_messages: undefined,
  delete_threads: [],
  move_threads: [],
  delete_messages: undefined,
  move_messages: undefined,
  delete_draft: undefined,
  create_label: {
    id: 'Label_1',
    name: 'Clients',
    kind: 'user',
    color: { text: '#ffffff', background: '#4a86e8' },
    messageCount: 0,
    unreadCount: 0,
  },
  rename_label: {
    id: 'Label_1',
    name: 'Clients',
    kind: 'user',
    color: { text: '#ffffff', background: '#4a86e8' },
    messageCount: 0,
    unreadCount: 0,
  },
  recolor_label: {
    id: 'Label_1',
    name: 'Clients',
    kind: 'user',
    color: { text: '#ffffff', background: '#fb4c2f' },
    messageCount: 0,
    unreadCount: 0,
  },
  delete_label: undefined,
  read_traversal_status: {
    accountId: '',
    state: 'notStarted',
    kind: null,
    discoveredCount: 0,
    persistedCount: 0,
    lastAdvancedAt: null,
    isResumed: false,
  },
  read_sender_avatar: null,
  read_account_avatar: null,
  search_threads: { items: [], nextCursor: null, previousCursor: null },
  search_total: 0,
  parse_search_query: {
    hasTextTerm: false,
    from: null,
    to: null,
    subject: null,
    includes: [],
    excludes: [],
    predicates: [],
  },
  read_queue_operations: [],
  cancel_queue_operation: true,
  retry_queue_operation: true,
  retry_failed_operations: 0,
  clear_queue_history: undefined,
  set_queue_paused: true,
  check_for_update: { currentVersion: '0.1.0', available: null },
  install_update: undefined,
};
