import type { IpcCommandMap } from '@/lib/types/ipc';
import { playwrightSidebarAccounts } from './accounts';
import { playwrightCreatedLabel, playwrightLabels, playwrightMutationResults } from './labels';
import { playwrightThreadPage } from './threads';
import { playwrightConversation } from './conversations';
import { playwrightSyncStatus, playwrightTriggerSyncResult } from './sync';
import { playwrightTraversalStatus } from './traversal';
import { playwrightSettings } from './settings';
import { playwrightLogEntries } from './logs';
import { playwrightContactSuggestions, playwrightStagedAttachment } from './compose';
import { playwrightCachedAttachment } from './attachments';
import {
  playwrightPausedQueueSummary,
  playwrightQueueOperationsSnapshot,
  playwrightQueueSummary,
  playwrightResumedQueueSummary,
} from './queue';

export const playwrightIpcFixtures: { [C in keyof IpcCommandMap]: IpcCommandMap[C]['result'] } = {
  health_check: { status: 'ok' },
  open_external_url: undefined,
  write_frontend_log: undefined,
  read_settings: playwrightSettings,
  write_setting: undefined,
  read_log_entries: playwrightLogEntries,
  pause_queue: playwrightPausedQueueSummary,
  resume_queue: playwrightResumedQueueSummary,
  read_queue_summary: playwrightQueueSummary,
  list_accounts: [],
  begin_sign_in: undefined,
  begin_reauthentication: undefined,
  remove_account: undefined,
  list_labels: playwrightLabels,
  lookup_contacts: playwrightContactSuggestions,
  reply_context: {
    to: [],
    cc: [],
    subject: '',
    originalMessageId: '',
    targetThreadId: null,
    inReplyTo: null,
    references: [],
    originalGmailMessageId: '',
    displayQuote: null,
    attachments: [],
  },
  stage_attachment_from_path: playwrightStagedAttachment,
  stage_attachment_from_bytes: playwrightStagedAttachment,
  stage_attachment_into_draft: playwrightStagedAttachment,
  release_staged_attachment: undefined,
  save_compose_draft: { operationId: 'draft-operation', draftId: 'draft-1' },
  send_compose_draft: { operationId: 'send-operation', draftId: 'draft-1' },
  discard_compose_draft: undefined,
  hydrate_compose_draft: {
    sessionId: 'session-1',
    accountId: 'account-1',
    draftId: 'draft-1',
    from: 'alex@example.com',
    to: [],
    cc: [],
    bcc: [],
    subject: '',
    html: '',
    quoteHtml: null,
    quotePlain: null,
    mode: 'draft',
    threadId: null,
    inReplyTo: null,
    references: [],
    originalMessageId: null,
    originalGmailMessageId: null,
    attachments: [],
  },
  'plugin:dialog|open': null,
  'plugin:dialog|save': null,
  ensure_attachment_cached: playwrightCachedAttachment,
  read_attachment_bytes: new ArrayBuffer(0),
  read_attachment_text: '',
  save_attachment_to_path: undefined,
  list_threads: playwrightThreadPage,
  load_conversation: playwrightConversation,
  fetch_message_body: undefined,
  trigger_sync: playwrightTriggerSyncResult,
  read_sync_status: playwrightSyncStatus,
  star_thread: undefined,
  unstar_thread: undefined,
  mark_thread_read: undefined,
  mark_thread_unread: undefined,
  mutate_threads: playwrightMutationResults,
  mutate_messages: undefined,
  delete_threads: playwrightMutationResults,
  move_threads: playwrightMutationResults,
  delete_messages: undefined,
  move_messages: undefined,
  delete_draft: undefined,
  create_label: playwrightCreatedLabel,
  rename_label: playwrightCreatedLabel,
  recolor_label: playwrightCreatedLabel,
  delete_label: undefined,
  read_traversal_status: playwrightTraversalStatus,
  read_sender_avatar: 'avatar-cache/senders/example-com.png',
  read_account_avatar: 'avatar-cache/accounts/account-1.png',
  search_threads: { items: [], nextCursor: null, total: 0 },
  parse_search_query: {
    hasTextTerm: false,
    from: null,
    to: null,
    subject: null,
    includes: [],
    excludes: [],
    predicates: [],
  },
  read_queue_operations: playwrightQueueOperationsSnapshot,
  cancel_queue_operation: true,
  retry_queue_operation: true,
  retry_failed_operations: 0,
  clear_queue_history: undefined,
  set_queue_paused: true,
};

export { playwrightSidebarAccounts };
