import type { IpcCommandMap, MailThread } from '@/lib/types/ipc';

export const playwrightThreads: MailThread[] = [
  {
    id: 'thread-1',
    subject: 'Q3 Marketing Strategy Review',
    sender: { display: 'Elena Rodriguez', address: 'elena.r@example.com' },
    sentRecipient: null,
    latestAt: Date.parse('2026-08-11T10:42:00Z'),
    messageCount: 3,
    isUnread: true,
    isStarred: true,
    hasAttachments: true,
    hasDraft: false,
    snippet: "I've attached the finalized slides for tomorrow's presentation.",
    labelIndicators: ['Work'],
  },
  {
    id: 'thread-2',
    subject: 'Updates to Color Tokens',
    sender: { display: 'Design Systems Guild', address: 'design-systems@example.com' },
    sentRecipient: null,
    latestAt: Date.parse('2026-08-10T09:00:00Z'),
    messageCount: 1,
    isUnread: false,
    isStarred: false,
    hasAttachments: false,
    hasDraft: false,
    snippet: 'Updated token names and contrast notes are ready for review.',
    labelIndicators: ['Work'],
  },
  {
    id: 'thread-3',
    subject: 'Action Required: 2FA Setup',
    sender: { display: 'Security Team', address: 'security@example.com' },
    sentRecipient: null,
    latestAt: Date.parse('2026-08-07T12:00:00Z'),
    messageCount: 1,
    isUnread: false,
    isStarred: false,
    hasAttachments: false,
    hasDraft: false,
    snippet: 'Please complete setup before the end of the week.',
    labelIndicators: ['Personal'],
  },
  {
    id: 'thread-4',
    subject: 'Lunch next week?',
    sender: { display: 'Alex Chen', address: 'alex.chen@example.com' },
    sentRecipient: null,
    latestAt: Date.parse('2026-07-31T15:30:00Z'),
    messageCount: 1,
    isUnread: false,
    isStarred: false,
    hasAttachments: false,
    hasDraft: false,
    snippet: 'Are you free next Tuesday?',
    labelIndicators: ['Personal'],
  },
];

export const playwrightThreadPage: IpcCommandMap['list_threads']['result'] = {
  items: playwrightThreads,
  nextCursor: null,
  previousCursor: null,
};
