/** Gmail's real 102-pair label colour palette (24 base colours + 78 extended "more colours" swatches).
 * Every id/name pair is accurate for its own hex value (Slice audit fix: the old table had 78
 * placeholder-named entries and a duplicate red/pink pair caused by a dropped grey). Position-aligned
 * 1:1 with `--color-label-gmail-{N}` in `src/index.css` and with `gmail::labels::LABEL_PALETTE` in Rust,
 * so a picked swatch id resolves to the identical Gmail colour pair on both sides of IPC. Classes are
 * literal so Tailwind emits every token. */
export type LabelColorId = string;
export type LabelColorSwatch = {
  id: LabelColorId;
  name: string;
  backgroundClass: string;
  textClass: string;
  dotClass: string;
  gmailBackground: string;
  gmailText: string;
};

export const LABEL_COLOR_PALETTE: LabelColorSwatch[] = [
  {
    id: 'black',
    name: 'Black',
    backgroundClass: 'bg-label-gmail-0 dark:bg-dark-label-gmail-0',
    textClass: 'text-label-on-gmail-0 dark:text-dark-label-on-gmail-0',
    dotClass: 'bg-label-gmail-0 dark:bg-dark-label-gmail-0',
    gmailBackground: '#000000',
    gmailText: '#ffffff',
  },
  {
    id: 'charcoal',
    name: 'Charcoal',
    backgroundClass: 'bg-label-gmail-1 dark:bg-dark-label-gmail-1',
    textClass: 'text-label-on-gmail-1 dark:text-dark-label-on-gmail-1',
    dotClass: 'bg-label-gmail-1 dark:bg-dark-label-gmail-1',
    gmailBackground: '#434343',
    gmailText: '#ffffff',
  },
  {
    id: 'slate-grey',
    name: 'Slate Grey',
    backgroundClass: 'bg-label-gmail-2 dark:bg-dark-label-gmail-2',
    textClass: 'text-label-on-gmail-2 dark:text-dark-label-on-gmail-2',
    dotClass: 'bg-label-gmail-2 dark:bg-dark-label-gmail-2',
    gmailBackground: '#666666',
    gmailText: '#ffffff',
  },
  {
    id: 'grey',
    name: 'Grey',
    backgroundClass: 'bg-label-gmail-3 dark:bg-dark-label-gmail-3',
    textClass: 'text-label-on-gmail-3 dark:text-dark-label-on-gmail-3',
    dotClass: 'bg-label-gmail-3 dark:bg-dark-label-gmail-3',
    gmailBackground: '#999999',
    gmailText: '#ffffff',
  },
  {
    id: 'silver',
    name: 'Silver',
    backgroundClass: 'bg-label-gmail-4 dark:bg-dark-label-gmail-4',
    textClass: 'text-label-on-gmail-4 dark:text-dark-label-on-gmail-4',
    dotClass: 'bg-label-gmail-4 dark:bg-dark-label-gmail-4',
    gmailBackground: '#cccccc',
    gmailText: '#000000',
  },
  {
    id: 'fog',
    name: 'Fog',
    backgroundClass: 'bg-label-gmail-5 dark:bg-dark-label-gmail-5',
    textClass: 'text-label-on-gmail-5 dark:text-dark-label-on-gmail-5',
    dotClass: 'bg-label-gmail-5 dark:bg-dark-label-gmail-5',
    gmailBackground: '#efefef',
    gmailText: '#000000',
  },
  {
    id: 'mist',
    name: 'Mist',
    backgroundClass: 'bg-label-gmail-6 dark:bg-dark-label-gmail-6',
    textClass: 'text-label-on-gmail-6 dark:text-dark-label-on-gmail-6',
    dotClass: 'bg-label-gmail-6 dark:bg-dark-label-gmail-6',
    gmailBackground: '#f3f3f3',
    gmailText: '#000000',
  },
  {
    id: 'white',
    name: 'White',
    backgroundClass: 'bg-label-gmail-7 dark:bg-dark-label-gmail-7',
    textClass: 'text-label-on-gmail-7 dark:text-dark-label-on-gmail-7',
    dotClass: 'bg-label-gmail-7 dark:bg-dark-label-gmail-7',
    gmailBackground: '#ffffff',
    gmailText: '#000000',
  },
  {
    id: 'red',
    name: 'Red',
    backgroundClass: 'bg-label-gmail-8 dark:bg-dark-label-gmail-8',
    textClass: 'text-label-on-gmail-8 dark:text-dark-label-on-gmail-8',
    dotClass: 'bg-label-gmail-8 dark:bg-dark-label-gmail-8',
    gmailBackground: '#fb4c2f',
    gmailText: '#ffffff',
  },
  {
    id: 'orange',
    name: 'Orange',
    backgroundClass: 'bg-label-gmail-9 dark:bg-dark-label-gmail-9',
    textClass: 'text-label-on-gmail-9 dark:text-dark-label-on-gmail-9',
    dotClass: 'bg-label-gmail-9 dark:bg-dark-label-gmail-9',
    gmailBackground: '#ffad47',
    gmailText: '#000000',
  },
  {
    id: 'amber',
    name: 'Amber',
    backgroundClass: 'bg-label-gmail-10 dark:bg-dark-label-gmail-10',
    textClass: 'text-label-on-gmail-10 dark:text-dark-label-on-gmail-10',
    dotClass: 'bg-label-gmail-10 dark:bg-dark-label-gmail-10',
    gmailBackground: '#fad165',
    gmailText: '#000000',
  },
  {
    id: 'green',
    name: 'Green',
    backgroundClass: 'bg-label-gmail-11 dark:bg-dark-label-gmail-11',
    textClass: 'text-label-on-gmail-11 dark:text-dark-label-on-gmail-11',
    dotClass: 'bg-label-gmail-11 dark:bg-dark-label-gmail-11',
    gmailBackground: '#16a766',
    gmailText: '#ffffff',
  },
  {
    id: 'mint',
    name: 'Mint',
    backgroundClass: 'bg-label-gmail-12 dark:bg-dark-label-gmail-12',
    textClass: 'text-label-on-gmail-12 dark:text-dark-label-on-gmail-12',
    dotClass: 'bg-label-gmail-12 dark:bg-dark-label-gmail-12',
    gmailBackground: '#43d692',
    gmailText: '#000000',
  },
  {
    id: 'blue',
    name: 'Blue',
    backgroundClass: 'bg-label-gmail-13 dark:bg-dark-label-gmail-13',
    textClass: 'text-label-on-gmail-13 dark:text-dark-label-on-gmail-13',
    dotClass: 'bg-label-gmail-13 dark:bg-dark-label-gmail-13',
    gmailBackground: '#4a86e8',
    gmailText: '#ffffff',
  },
  {
    id: 'purple',
    name: 'Purple',
    backgroundClass: 'bg-label-gmail-14 dark:bg-dark-label-gmail-14',
    textClass: 'text-label-on-gmail-14 dark:text-dark-label-on-gmail-14',
    dotClass: 'bg-label-gmail-14 dark:bg-dark-label-gmail-14',
    gmailBackground: '#a479e2',
    gmailText: '#ffffff',
  },
  {
    id: 'pink',
    name: 'Pink',
    backgroundClass: 'bg-label-gmail-15 dark:bg-dark-label-gmail-15',
    textClass: 'text-label-on-gmail-15 dark:text-dark-label-on-gmail-15',
    dotClass: 'bg-label-gmail-15 dark:bg-dark-label-gmail-15',
    gmailBackground: '#f691b3',
    gmailText: '#000000',
  },
  {
    id: 'peach',
    name: 'Peach',
    backgroundClass: 'bg-label-gmail-16 dark:bg-dark-label-gmail-16',
    textClass: 'text-label-on-gmail-16 dark:text-dark-label-on-gmail-16',
    dotClass: 'bg-label-gmail-16 dark:bg-dark-label-gmail-16',
    gmailBackground: '#f6c5be',
    gmailText: '#000000',
  },
  {
    id: 'cream',
    name: 'Cream',
    backgroundClass: 'bg-label-gmail-17 dark:bg-dark-label-gmail-17',
    textClass: 'text-label-on-gmail-17 dark:text-dark-label-on-gmail-17',
    dotClass: 'bg-label-gmail-17 dark:bg-dark-label-gmail-17',
    gmailBackground: '#ffe6c7',
    gmailText: '#000000',
  },
  {
    id: 'butter',
    name: 'Butter',
    backgroundClass: 'bg-label-gmail-18 dark:bg-dark-label-gmail-18',
    textClass: 'text-label-on-gmail-18 dark:text-dark-label-on-gmail-18',
    dotClass: 'bg-label-gmail-18 dark:bg-dark-label-gmail-18',
    gmailBackground: '#fef1d1',
    gmailText: '#000000',
  },
  {
    id: 'sage',
    name: 'Sage',
    backgroundClass: 'bg-label-gmail-19 dark:bg-dark-label-gmail-19',
    textClass: 'text-label-on-gmail-19 dark:text-dark-label-on-gmail-19',
    dotClass: 'bg-label-gmail-19 dark:bg-dark-label-gmail-19',
    gmailBackground: '#b9e4d0',
    gmailText: '#000000',
  },
  {
    id: 'seafoam',
    name: 'Seafoam',
    backgroundClass: 'bg-label-gmail-20 dark:bg-dark-label-gmail-20',
    textClass: 'text-label-on-gmail-20 dark:text-dark-label-on-gmail-20',
    dotClass: 'bg-label-gmail-20 dark:bg-dark-label-gmail-20',
    gmailBackground: '#c6f3de',
    gmailText: '#000000',
  },
  {
    id: 'sky',
    name: 'Sky',
    backgroundClass: 'bg-label-gmail-21 dark:bg-dark-label-gmail-21',
    textClass: 'text-label-on-gmail-21 dark:text-dark-label-on-gmail-21',
    dotClass: 'bg-label-gmail-21 dark:bg-dark-label-gmail-21',
    gmailBackground: '#c9daf8',
    gmailText: '#000000',
  },
  {
    id: 'lavender',
    name: 'Lavender',
    backgroundClass: 'bg-label-gmail-22 dark:bg-dark-label-gmail-22',
    textClass: 'text-label-on-gmail-22 dark:text-dark-label-on-gmail-22',
    dotClass: 'bg-label-gmail-22 dark:bg-dark-label-gmail-22',
    gmailBackground: '#e4d7f5',
    gmailText: '#000000',
  },
  {
    id: 'blush',
    name: 'Blush',
    backgroundClass: 'bg-label-gmail-23 dark:bg-dark-label-gmail-23',
    textClass: 'text-label-on-gmail-23 dark:text-dark-label-on-gmail-23',
    dotClass: 'bg-label-gmail-23 dark:bg-dark-label-gmail-23',
    gmailBackground: '#fcdee8',
    gmailText: '#000000',
  },
  {
    id: 'light-red',
    name: 'Light Red',
    backgroundClass: 'bg-label-gmail-24 dark:bg-dark-label-gmail-24',
    textClass: 'text-label-on-gmail-24 dark:text-dark-label-on-gmail-24',
    dotClass: 'bg-label-gmail-24 dark:bg-dark-label-gmail-24',
    gmailBackground: '#efa093',
    gmailText: '#000000',
  },
  {
    id: 'light-orange',
    name: 'Light Orange',
    backgroundClass: 'bg-label-gmail-25 dark:bg-dark-label-gmail-25',
    textClass: 'text-label-on-gmail-25 dark:text-dark-label-on-gmail-25',
    dotClass: 'bg-label-gmail-25 dark:bg-dark-label-gmail-25',
    gmailBackground: '#ffd6a2',
    gmailText: '#000000',
  },
  {
    id: 'light-amber',
    name: 'Light Amber',
    backgroundClass: 'bg-label-gmail-26 dark:bg-dark-label-gmail-26',
    textClass: 'text-label-on-gmail-26 dark:text-dark-label-on-gmail-26',
    dotClass: 'bg-label-gmail-26 dark:bg-dark-label-gmail-26',
    gmailBackground: '#fce8b3',
    gmailText: '#000000',
  },
  {
    id: 'emerald',
    name: 'Emerald',
    backgroundClass: 'bg-label-gmail-27 dark:bg-dark-label-gmail-27',
    textClass: 'text-label-on-gmail-27 dark:text-dark-label-on-gmail-27',
    dotClass: 'bg-label-gmail-27 dark:bg-dark-label-gmail-27',
    gmailBackground: '#89d3b2',
    gmailText: '#000000',
  },
  {
    id: 'light-emerald',
    name: 'Light Emerald',
    backgroundClass: 'bg-label-gmail-28 dark:bg-dark-label-gmail-28',
    textClass: 'text-label-on-gmail-28 dark:text-dark-label-on-gmail-28',
    dotClass: 'bg-label-gmail-28 dark:bg-dark-label-gmail-28',
    gmailBackground: '#a0eac9',
    gmailText: '#000000',
  },
  {
    id: 'light-blue',
    name: 'Light Blue',
    backgroundClass: 'bg-label-gmail-29 dark:bg-dark-label-gmail-29',
    textClass: 'text-label-on-gmail-29 dark:text-dark-label-on-gmail-29',
    dotClass: 'bg-label-gmail-29 dark:bg-dark-label-gmail-29',
    gmailBackground: '#a4c2f4',
    gmailText: '#000000',
  },
  {
    id: 'light-violet',
    name: 'Light Violet',
    backgroundClass: 'bg-label-gmail-30 dark:bg-dark-label-gmail-30',
    textClass: 'text-label-on-gmail-30 dark:text-dark-label-on-gmail-30',
    dotClass: 'bg-label-gmail-30 dark:bg-dark-label-gmail-30',
    gmailBackground: '#d0bcf1',
    gmailText: '#000000',
  },
  {
    id: 'pale-rose',
    name: 'Pale Rose',
    backgroundClass: 'bg-label-gmail-31 dark:bg-dark-label-gmail-31',
    textClass: 'text-label-on-gmail-31 dark:text-dark-label-on-gmail-31',
    dotClass: 'bg-label-gmail-31 dark:bg-dark-label-gmail-31',
    gmailBackground: '#fbc8d9',
    gmailText: '#000000',
  },
  {
    id: 'red-2',
    name: 'Red 2',
    backgroundClass: 'bg-label-gmail-32 dark:bg-dark-label-gmail-32',
    textClass: 'text-label-on-gmail-32 dark:text-dark-label-on-gmail-32',
    dotClass: 'bg-label-gmail-32 dark:bg-dark-label-gmail-32',
    gmailBackground: '#e66550',
    gmailText: '#ffffff',
  },
  {
    id: 'orange-2',
    name: 'Orange 2',
    backgroundClass: 'bg-label-gmail-33 dark:bg-dark-label-gmail-33',
    textClass: 'text-label-on-gmail-33 dark:text-dark-label-on-gmail-33',
    dotClass: 'bg-label-gmail-33 dark:bg-dark-label-gmail-33',
    gmailBackground: '#ffbc6b',
    gmailText: '#000000',
  },
  {
    id: 'light-amber-2',
    name: 'Light Amber 2',
    backgroundClass: 'bg-label-gmail-34 dark:bg-dark-label-gmail-34',
    textClass: 'text-label-on-gmail-34 dark:text-dark-label-on-gmail-34',
    dotClass: 'bg-label-gmail-34 dark:bg-dark-label-gmail-34',
    gmailBackground: '#fcda83',
    gmailText: '#000000',
  },
  {
    id: 'deep-emerald',
    name: 'Deep Emerald',
    backgroundClass: 'bg-label-gmail-35 dark:bg-dark-label-gmail-35',
    textClass: 'text-label-on-gmail-35 dark:text-dark-label-on-gmail-35',
    dotClass: 'bg-label-gmail-35 dark:bg-dark-label-gmail-35',
    gmailBackground: '#44b984',
    gmailText: '#ffffff',
  },
  {
    id: 'emerald-2',
    name: 'Emerald 2',
    backgroundClass: 'bg-label-gmail-36 dark:bg-dark-label-gmail-36',
    textClass: 'text-label-on-gmail-36 dark:text-dark-label-on-gmail-36',
    dotClass: 'bg-label-gmail-36 dark:bg-dark-label-gmail-36',
    gmailBackground: '#68dfa9',
    gmailText: '#000000',
  },
  {
    id: 'blue-2',
    name: 'Blue 2',
    backgroundClass: 'bg-label-gmail-37 dark:bg-dark-label-gmail-37',
    textClass: 'text-label-on-gmail-37 dark:text-dark-label-on-gmail-37',
    dotClass: 'bg-label-gmail-37 dark:bg-dark-label-gmail-37',
    gmailBackground: '#6d9eeb',
    gmailText: '#ffffff',
  },
  {
    id: 'violet',
    name: 'Violet',
    backgroundClass: 'bg-label-gmail-38 dark:bg-dark-label-gmail-38',
    textClass: 'text-label-on-gmail-38 dark:text-dark-label-on-gmail-38',
    dotClass: 'bg-label-gmail-38 dark:bg-dark-label-gmail-38',
    gmailBackground: '#b694e8',
    gmailText: '#000000',
  },
  {
    id: 'light-rose',
    name: 'Light Rose',
    backgroundClass: 'bg-label-gmail-39 dark:bg-dark-label-gmail-39',
    textClass: 'text-label-on-gmail-39 dark:text-dark-label-on-gmail-39',
    dotClass: 'bg-label-gmail-39 dark:bg-dark-label-gmail-39',
    gmailBackground: '#f7a7c0',
    gmailText: '#000000',
  },
  {
    id: 'deep-red',
    name: 'Deep Red',
    backgroundClass: 'bg-label-gmail-40 dark:bg-dark-label-gmail-40',
    textClass: 'text-label-on-gmail-40 dark:text-dark-label-on-gmail-40',
    dotClass: 'bg-label-gmail-40 dark:bg-dark-label-gmail-40',
    gmailBackground: '#cc3a21',
    gmailText: '#ffffff',
  },
  {
    id: 'orange-3',
    name: 'Orange 3',
    backgroundClass: 'bg-label-gmail-41 dark:bg-dark-label-gmail-41',
    textClass: 'text-label-on-gmail-41 dark:text-dark-label-on-gmail-41',
    dotClass: 'bg-label-gmail-41 dark:bg-dark-label-gmail-41',
    gmailBackground: '#eaa041',
    gmailText: '#000000',
  },
  {
    id: 'amber-2',
    name: 'Amber 2',
    backgroundClass: 'bg-label-gmail-42 dark:bg-dark-label-gmail-42',
    textClass: 'text-label-on-gmail-42 dark:text-dark-label-on-gmail-42',
    dotClass: 'bg-label-gmail-42 dark:bg-dark-label-gmail-42',
    gmailBackground: '#f2c960',
    gmailText: '#000000',
  },
  {
    id: 'dark-emerald',
    name: 'Dark Emerald',
    backgroundClass: 'bg-label-gmail-43 dark:bg-dark-label-gmail-43',
    textClass: 'text-label-on-gmail-43 dark:text-dark-label-on-gmail-43',
    dotClass: 'bg-label-gmail-43 dark:bg-dark-label-gmail-43',
    gmailBackground: '#149e60',
    gmailText: '#ffffff',
  },
  {
    id: 'deep-emerald-2',
    name: 'Deep Emerald 2',
    backgroundClass: 'bg-label-gmail-44 dark:bg-dark-label-gmail-44',
    textClass: 'text-label-on-gmail-44 dark:text-dark-label-on-gmail-44',
    dotClass: 'bg-label-gmail-44 dark:bg-dark-label-gmail-44',
    gmailBackground: '#3dc789',
    gmailText: '#ffffff',
  },
  {
    id: 'deep-blue',
    name: 'Deep Blue',
    backgroundClass: 'bg-label-gmail-45 dark:bg-dark-label-gmail-45',
    textClass: 'text-label-on-gmail-45 dark:text-dark-label-on-gmail-45',
    dotClass: 'bg-label-gmail-45 dark:bg-dark-label-gmail-45',
    gmailBackground: '#3c78d8',
    gmailText: '#ffffff',
  },
  {
    id: 'violet-2',
    name: 'Violet 2',
    backgroundClass: 'bg-label-gmail-46 dark:bg-dark-label-gmail-46',
    textClass: 'text-label-on-gmail-46 dark:text-dark-label-on-gmail-46',
    dotClass: 'bg-label-gmail-46 dark:bg-dark-label-gmail-46',
    gmailBackground: '#8e63ce',
    gmailText: '#ffffff',
  },
  {
    id: 'rose',
    name: 'Rose',
    backgroundClass: 'bg-label-gmail-47 dark:bg-dark-label-gmail-47',
    textClass: 'text-label-on-gmail-47 dark:text-dark-label-on-gmail-47',
    dotClass: 'bg-label-gmail-47 dark:bg-dark-label-gmail-47',
    gmailBackground: '#e07798',
    gmailText: '#ffffff',
  },
  {
    id: 'deep-red-2',
    name: 'Deep Red 2',
    backgroundClass: 'bg-label-gmail-48 dark:bg-dark-label-gmail-48',
    textClass: 'text-label-on-gmail-48 dark:text-dark-label-on-gmail-48',
    dotClass: 'bg-label-gmail-48 dark:bg-dark-label-gmail-48',
    gmailBackground: '#ac2b16',
    gmailText: '#ffffff',
  },
  {
    id: 'deep-orange',
    name: 'Deep Orange',
    backgroundClass: 'bg-label-gmail-49 dark:bg-dark-label-gmail-49',
    textClass: 'text-label-on-gmail-49 dark:text-dark-label-on-gmail-49',
    dotClass: 'bg-label-gmail-49 dark:bg-dark-label-gmail-49',
    gmailBackground: '#cf8933',
    gmailText: '#ffffff',
  },
  {
    id: 'amber-3',
    name: 'Amber 3',
    backgroundClass: 'bg-label-gmail-50 dark:bg-dark-label-gmail-50',
    textClass: 'text-label-on-gmail-50 dark:text-dark-label-on-gmail-50',
    dotClass: 'bg-label-gmail-50 dark:bg-dark-label-gmail-50',
    gmailBackground: '#d5ae49',
    gmailText: '#000000',
  },
  {
    id: 'dark-emerald-2',
    name: 'Dark Emerald 2',
    backgroundClass: 'bg-label-gmail-51 dark:bg-dark-label-gmail-51',
    textClass: 'text-label-on-gmail-51 dark:text-dark-label-on-gmail-51',
    dotClass: 'bg-label-gmail-51 dark:bg-dark-label-gmail-51',
    gmailBackground: '#0b804b',
    gmailText: '#ffffff',
  },
  {
    id: 'deep-emerald-3',
    name: 'Deep Emerald 3',
    backgroundClass: 'bg-label-gmail-52 dark:bg-dark-label-gmail-52',
    textClass: 'text-label-on-gmail-52 dark:text-dark-label-on-gmail-52',
    dotClass: 'bg-label-gmail-52 dark:bg-dark-label-gmail-52',
    gmailBackground: '#2a9c68',
    gmailText: '#ffffff',
  },
  {
    id: 'deep-blue-2',
    name: 'Deep Blue 2',
    backgroundClass: 'bg-label-gmail-53 dark:bg-dark-label-gmail-53',
    textClass: 'text-label-on-gmail-53 dark:text-dark-label-on-gmail-53',
    dotClass: 'bg-label-gmail-53 dark:bg-dark-label-gmail-53',
    gmailBackground: '#285bac',
    gmailText: '#ffffff',
  },
  {
    id: 'deep-violet',
    name: 'Deep Violet',
    backgroundClass: 'bg-label-gmail-54 dark:bg-dark-label-gmail-54',
    textClass: 'text-label-on-gmail-54 dark:text-dark-label-on-gmail-54',
    dotClass: 'bg-label-gmail-54 dark:bg-dark-label-gmail-54',
    gmailBackground: '#653e9b',
    gmailText: '#ffffff',
  },
  {
    id: 'deep-rose',
    name: 'Deep Rose',
    backgroundClass: 'bg-label-gmail-55 dark:bg-dark-label-gmail-55',
    textClass: 'text-label-on-gmail-55 dark:text-dark-label-on-gmail-55',
    dotClass: 'bg-label-gmail-55 dark:bg-dark-label-gmail-55',
    gmailBackground: '#b65775',
    gmailText: '#ffffff',
  },
  {
    id: 'dark-red',
    name: 'Dark Red',
    backgroundClass: 'bg-label-gmail-56 dark:bg-dark-label-gmail-56',
    textClass: 'text-label-on-gmail-56 dark:text-dark-label-on-gmail-56',
    dotClass: 'bg-label-gmail-56 dark:bg-dark-label-gmail-56',
    gmailBackground: '#822111',
    gmailText: '#ffffff',
  },
  {
    id: 'deep-orange-2',
    name: 'Deep Orange 2',
    backgroundClass: 'bg-label-gmail-57 dark:bg-dark-label-gmail-57',
    textClass: 'text-label-on-gmail-57 dark:text-dark-label-on-gmail-57',
    dotClass: 'bg-label-gmail-57 dark:bg-dark-label-gmail-57',
    gmailBackground: '#a46a21',
    gmailText: '#ffffff',
  },
  {
    id: 'deep-amber',
    name: 'Deep Amber',
    backgroundClass: 'bg-label-gmail-58 dark:bg-dark-label-gmail-58',
    textClass: 'text-label-on-gmail-58 dark:text-dark-label-on-gmail-58',
    dotClass: 'bg-label-gmail-58 dark:bg-dark-label-gmail-58',
    gmailBackground: '#aa8831',
    gmailText: '#ffffff',
  },
  {
    id: 'dark-emerald-3',
    name: 'Dark Emerald 3',
    backgroundClass: 'bg-label-gmail-59 dark:bg-dark-label-gmail-59',
    textClass: 'text-label-on-gmail-59 dark:text-dark-label-on-gmail-59',
    dotClass: 'bg-label-gmail-59 dark:bg-dark-label-gmail-59',
    gmailBackground: '#076239',
    gmailText: '#ffffff',
  },
  {
    id: 'dark-emerald-4',
    name: 'Dark Emerald 4',
    backgroundClass: 'bg-label-gmail-60 dark:bg-dark-label-gmail-60',
    textClass: 'text-label-on-gmail-60 dark:text-dark-label-on-gmail-60',
    dotClass: 'bg-label-gmail-60 dark:bg-dark-label-gmail-60',
    gmailBackground: '#1a764d',
    gmailText: '#ffffff',
  },
  {
    id: 'dark-blue',
    name: 'Dark Blue',
    backgroundClass: 'bg-label-gmail-61 dark:bg-dark-label-gmail-61',
    textClass: 'text-label-on-gmail-61 dark:text-dark-label-on-gmail-61',
    dotClass: 'bg-label-gmail-61 dark:bg-dark-label-gmail-61',
    gmailBackground: '#1c4587',
    gmailText: '#ffffff',
  },
  {
    id: 'dark-violet',
    name: 'Dark Violet',
    backgroundClass: 'bg-label-gmail-62 dark:bg-dark-label-gmail-62',
    textClass: 'text-label-on-gmail-62 dark:text-dark-label-on-gmail-62',
    dotClass: 'bg-label-gmail-62 dark:bg-dark-label-gmail-62',
    gmailBackground: '#41236d',
    gmailText: '#ffffff',
  },
  {
    id: 'deep-rose-2',
    name: 'Deep Rose 2',
    backgroundClass: 'bg-label-gmail-63 dark:bg-dark-label-gmail-63',
    textClass: 'text-label-on-gmail-63 dark:text-dark-label-on-gmail-63',
    dotClass: 'bg-label-gmail-63 dark:bg-dark-label-gmail-63',
    gmailBackground: '#83334c',
    gmailText: '#ffffff',
  },
  {
    id: 'graphite',
    name: 'Graphite',
    backgroundClass: 'bg-label-gmail-64 dark:bg-dark-label-gmail-64',
    textClass: 'text-label-on-gmail-64 dark:text-dark-label-on-gmail-64',
    dotClass: 'bg-label-gmail-64 dark:bg-dark-label-gmail-64',
    gmailBackground: '#464646',
    gmailText: '#ffffff',
  },
  {
    id: 'fog-2',
    name: 'Fog 2',
    backgroundClass: 'bg-label-gmail-65 dark:bg-dark-label-gmail-65',
    textClass: 'text-label-on-gmail-65 dark:text-dark-label-on-gmail-65',
    dotClass: 'bg-label-gmail-65 dark:bg-dark-label-gmail-65',
    gmailBackground: '#e7e7e7',
    gmailText: '#000000',
  },
  {
    id: 'dark-blue-2',
    name: 'Dark Blue 2',
    backgroundClass: 'bg-label-gmail-66 dark:bg-dark-label-gmail-66',
    textClass: 'text-label-on-gmail-66 dark:text-dark-label-on-gmail-66',
    dotClass: 'bg-label-gmail-66 dark:bg-dark-label-gmail-66',
    gmailBackground: '#0d3472',
    gmailText: '#ffffff',
  },
  {
    id: 'light-blue-2',
    name: 'Light Blue 2',
    backgroundClass: 'bg-label-gmail-67 dark:bg-dark-label-gmail-67',
    textClass: 'text-label-on-gmail-67 dark:text-dark-label-on-gmail-67',
    dotClass: 'bg-label-gmail-67 dark:bg-dark-label-gmail-67',
    gmailBackground: '#b6cff5',
    gmailText: '#000000',
  },
  {
    id: 'dark-cyan',
    name: 'Dark Cyan',
    backgroundClass: 'bg-label-gmail-68 dark:bg-dark-label-gmail-68',
    textClass: 'text-label-on-gmail-68 dark:text-dark-label-on-gmail-68',
    dotClass: 'bg-label-gmail-68 dark:bg-dark-label-gmail-68',
    gmailBackground: '#0d3b44',
    gmailText: '#ffffff',
  },
  {
    id: 'cyan',
    name: 'Cyan',
    backgroundClass: 'bg-label-gmail-69 dark:bg-dark-label-gmail-69',
    textClass: 'text-label-on-gmail-69 dark:text-dark-label-on-gmail-69',
    dotClass: 'bg-label-gmail-69 dark:bg-dark-label-gmail-69',
    gmailBackground: '#98d7e4',
    gmailText: '#000000',
  },
  {
    id: 'dark-violet-2',
    name: 'Dark Violet 2',
    backgroundClass: 'bg-label-gmail-70 dark:bg-dark-label-gmail-70',
    textClass: 'text-label-on-gmail-70 dark:text-dark-label-on-gmail-70',
    dotClass: 'bg-label-gmail-70 dark:bg-dark-label-gmail-70',
    gmailBackground: '#3d188e',
    gmailText: '#ffffff',
  },
  {
    id: 'pale-violet',
    name: 'Pale Violet',
    backgroundClass: 'bg-label-gmail-71 dark:bg-dark-label-gmail-71',
    textClass: 'text-label-on-gmail-71 dark:text-dark-label-on-gmail-71',
    dotClass: 'bg-label-gmail-71 dark:bg-dark-label-gmail-71',
    gmailBackground: '#e3d7ff',
    gmailText: '#000000',
  },
  {
    id: 'dark-rose',
    name: 'Dark Rose',
    backgroundClass: 'bg-label-gmail-72 dark:bg-dark-label-gmail-72',
    textClass: 'text-label-on-gmail-72 dark:text-dark-label-on-gmail-72',
    dotClass: 'bg-label-gmail-72 dark:bg-dark-label-gmail-72',
    gmailBackground: '#711a36',
    gmailText: '#ffffff',
  },
  {
    id: 'pale-rose-2',
    name: 'Pale Rose 2',
    backgroundClass: 'bg-label-gmail-73 dark:bg-dark-label-gmail-73',
    textClass: 'text-label-on-gmail-73 dark:text-dark-label-on-gmail-73',
    dotClass: 'bg-label-gmail-73 dark:bg-dark-label-gmail-73',
    gmailBackground: '#fbd3e0',
    gmailText: '#000000',
  },
  {
    id: 'dark-red-2',
    name: 'Dark Red 2',
    backgroundClass: 'bg-label-gmail-74 dark:bg-dark-label-gmail-74',
    textClass: 'text-label-on-gmail-74 dark:text-dark-label-on-gmail-74',
    dotClass: 'bg-label-gmail-74 dark:bg-dark-label-gmail-74',
    gmailBackground: '#8a1c0a',
    gmailText: '#ffffff',
  },
  {
    id: 'light-red-2',
    name: 'Light Red 2',
    backgroundClass: 'bg-label-gmail-75 dark:bg-dark-label-gmail-75',
    textClass: 'text-label-on-gmail-75 dark:text-dark-label-on-gmail-75',
    dotClass: 'bg-label-gmail-75 dark:bg-dark-label-gmail-75',
    gmailBackground: '#f2b2a8',
    gmailText: '#000000',
  },
  {
    id: 'dark-orange',
    name: 'Dark Orange',
    backgroundClass: 'bg-label-gmail-76 dark:bg-dark-label-gmail-76',
    textClass: 'text-label-on-gmail-76 dark:text-dark-label-on-gmail-76',
    dotClass: 'bg-label-gmail-76 dark:bg-dark-label-gmail-76',
    gmailBackground: '#7a2e0b',
    gmailText: '#ffffff',
  },
  {
    id: 'light-orange-2',
    name: 'Light Orange 2',
    backgroundClass: 'bg-label-gmail-77 dark:bg-dark-label-gmail-77',
    textClass: 'text-label-on-gmail-77 dark:text-dark-label-on-gmail-77',
    dotClass: 'bg-label-gmail-77 dark:bg-dark-label-gmail-77',
    gmailBackground: '#ffc8af',
    gmailText: '#000000',
  },
  {
    id: 'dark-orange-2',
    name: 'Dark Orange 2',
    backgroundClass: 'bg-label-gmail-78 dark:bg-dark-label-gmail-78',
    textClass: 'text-label-on-gmail-78 dark:text-dark-label-on-gmail-78',
    dotClass: 'bg-label-gmail-78 dark:bg-dark-label-gmail-78',
    gmailBackground: '#7a4706',
    gmailText: '#ffffff',
  },
  {
    id: 'light-orange-3',
    name: 'Light Orange 3',
    backgroundClass: 'bg-label-gmail-79 dark:bg-dark-label-gmail-79',
    textClass: 'text-label-on-gmail-79 dark:text-dark-label-on-gmail-79',
    dotClass: 'bg-label-gmail-79 dark:bg-dark-label-gmail-79',
    gmailBackground: '#ffdeb5',
    gmailText: '#000000',
  },
  {
    id: 'dark-gold',
    name: 'Dark Gold',
    backgroundClass: 'bg-label-gmail-80 dark:bg-dark-label-gmail-80',
    textClass: 'text-label-on-gmail-80 dark:text-dark-label-on-gmail-80',
    dotClass: 'bg-label-gmail-80 dark:bg-dark-label-gmail-80',
    gmailBackground: '#594c05',
    gmailText: '#ffffff',
  },
  {
    id: 'gold',
    name: 'Gold',
    backgroundClass: 'bg-label-gmail-81 dark:bg-dark-label-gmail-81',
    textClass: 'text-label-on-gmail-81 dark:text-dark-label-on-gmail-81',
    dotClass: 'bg-label-gmail-81 dark:bg-dark-label-gmail-81',
    gmailBackground: '#fbe983',
    gmailText: '#000000',
  },
  {
    id: 'dark-amber',
    name: 'Dark Amber',
    backgroundClass: 'bg-label-gmail-82 dark:bg-dark-label-gmail-82',
    textClass: 'text-label-on-gmail-82 dark:text-dark-label-on-gmail-82',
    dotClass: 'bg-label-gmail-82 dark:bg-dark-label-gmail-82',
    gmailBackground: '#684e07',
    gmailText: '#ffffff',
  },
  {
    id: 'light-amber-3',
    name: 'Light Amber 3',
    backgroundClass: 'bg-label-gmail-83 dark:bg-dark-label-gmail-83',
    textClass: 'text-label-on-gmail-83 dark:text-dark-label-on-gmail-83',
    dotClass: 'bg-label-gmail-83 dark:bg-dark-label-gmail-83',
    gmailBackground: '#fdedc1',
    gmailText: '#000000',
  },
  {
    id: 'dark-emerald-5',
    name: 'Dark Emerald 5',
    backgroundClass: 'bg-label-gmail-84 dark:bg-dark-label-gmail-84',
    textClass: 'text-label-on-gmail-84 dark:text-dark-label-on-gmail-84',
    dotClass: 'bg-label-gmail-84 dark:bg-dark-label-gmail-84',
    gmailBackground: '#0b4f30',
    gmailText: '#ffffff',
  },
  {
    id: 'light-emerald-2',
    name: 'Light Emerald 2',
    backgroundClass: 'bg-label-gmail-85 dark:bg-dark-label-gmail-85',
    textClass: 'text-label-on-gmail-85 dark:text-dark-label-on-gmail-85',
    dotClass: 'bg-label-gmail-85 dark:bg-dark-label-gmail-85',
    gmailBackground: '#b3efd3',
    gmailText: '#000000',
  },
  {
    id: 'dark-emerald-6',
    name: 'Dark Emerald 6',
    backgroundClass: 'bg-label-gmail-86 dark:bg-dark-label-gmail-86',
    textClass: 'text-label-on-gmail-86 dark:text-dark-label-on-gmail-86',
    dotClass: 'bg-label-gmail-86 dark:bg-dark-label-gmail-86',
    gmailBackground: '#04502e',
    gmailText: '#ffffff',
  },
  {
    id: 'emerald-3',
    name: 'Emerald 3',
    backgroundClass: 'bg-label-gmail-87 dark:bg-dark-label-gmail-87',
    textClass: 'text-label-on-gmail-87 dark:text-dark-label-on-gmail-87',
    dotClass: 'bg-label-gmail-87 dark:bg-dark-label-gmail-87',
    gmailBackground: '#a2dcc1',
    gmailText: '#000000',
  },
  {
    id: 'silver-2',
    name: 'Silver 2',
    backgroundClass: 'bg-label-gmail-88 dark:bg-dark-label-gmail-88',
    textClass: 'text-label-on-gmail-88 dark:text-dark-label-on-gmail-88',
    dotClass: 'bg-label-gmail-88 dark:bg-dark-label-gmail-88',
    gmailBackground: '#c2c2c2',
    gmailText: '#000000',
  },
  {
    id: 'blue-3',
    name: 'Blue 3',
    backgroundClass: 'bg-label-gmail-89 dark:bg-dark-label-gmail-89',
    textClass: 'text-label-on-gmail-89 dark:text-dark-label-on-gmail-89',
    dotClass: 'bg-label-gmail-89 dark:bg-dark-label-gmail-89',
    gmailBackground: '#4986e7',
    gmailText: '#ffffff',
  },
  {
    id: 'deep-cyan',
    name: 'Deep Cyan',
    backgroundClass: 'bg-label-gmail-90 dark:bg-dark-label-gmail-90',
    textClass: 'text-label-on-gmail-90 dark:text-dark-label-on-gmail-90',
    dotClass: 'bg-label-gmail-90 dark:bg-dark-label-gmail-90',
    gmailBackground: '#2da2bb',
    gmailText: '#ffffff',
  },
  {
    id: 'light-violet-2',
    name: 'Light Violet 2',
    backgroundClass: 'bg-label-gmail-91 dark:bg-dark-label-gmail-91',
    textClass: 'text-label-on-gmail-91 dark:text-dark-label-on-gmail-91',
    dotClass: 'bg-label-gmail-91 dark:bg-dark-label-gmail-91',
    gmailBackground: '#b99aff',
    gmailText: '#000000',
  },
  {
    id: 'deep-rose-3',
    name: 'Deep Rose 3',
    backgroundClass: 'bg-label-gmail-92 dark:bg-dark-label-gmail-92',
    textClass: 'text-label-on-gmail-92 dark:text-dark-label-on-gmail-92',
    dotClass: 'bg-label-gmail-92 dark:bg-dark-label-gmail-92',
    gmailBackground: '#994a64',
    gmailText: '#ffffff',
  },
  {
    id: 'light-rose-2',
    name: 'Light Rose 2',
    backgroundClass: 'bg-label-gmail-93 dark:bg-dark-label-gmail-93',
    textClass: 'text-label-on-gmail-93 dark:text-dark-label-on-gmail-93',
    dotClass: 'bg-label-gmail-93 dark:bg-dark-label-gmail-93',
    gmailBackground: '#f691b2',
    gmailText: '#000000',
  },
  {
    id: 'orange-4',
    name: 'Orange 4',
    backgroundClass: 'bg-label-gmail-94 dark:bg-dark-label-gmail-94',
    textClass: 'text-label-on-gmail-94 dark:text-dark-label-on-gmail-94',
    dotClass: 'bg-label-gmail-94 dark:bg-dark-label-gmail-94',
    gmailBackground: '#ff7537',
    gmailText: '#ffffff',
  },
  {
    id: 'orange-5',
    name: 'Orange 5',
    backgroundClass: 'bg-label-gmail-95 dark:bg-dark-label-gmail-95',
    textClass: 'text-label-on-gmail-95 dark:text-dark-label-on-gmail-95',
    dotClass: 'bg-label-gmail-95 dark:bg-dark-label-gmail-95',
    gmailBackground: '#ffad46',
    gmailText: '#000000',
  },
  {
    id: 'dark-red-3',
    name: 'Dark Red 3',
    backgroundClass: 'bg-label-gmail-96 dark:bg-dark-label-gmail-96',
    textClass: 'text-label-on-gmail-96 dark:text-dark-label-on-gmail-96',
    dotClass: 'bg-label-gmail-96 dark:bg-dark-label-gmail-96',
    gmailBackground: '#662e37',
    gmailText: '#ffffff',
  },
  {
    id: 'pale-red',
    name: 'Pale Red',
    backgroundClass: 'bg-label-gmail-97 dark:bg-dark-label-gmail-97',
    textClass: 'text-label-on-gmail-97 dark:text-dark-label-on-gmail-97',
    dotClass: 'bg-label-gmail-97 dark:bg-dark-label-gmail-97',
    gmailBackground: '#ebdbde',
    gmailText: '#000000',
  },
  {
    id: 'red-3',
    name: 'Red 3',
    backgroundClass: 'bg-label-gmail-98 dark:bg-dark-label-gmail-98',
    textClass: 'text-label-on-gmail-98 dark:text-dark-label-on-gmail-98',
    dotClass: 'bg-label-gmail-98 dark:bg-dark-label-gmail-98',
    gmailBackground: '#cca6ac',
    gmailText: '#000000',
  },
  {
    id: 'dark-emerald-7',
    name: 'Dark Emerald 7',
    backgroundClass: 'bg-label-gmail-99 dark:bg-dark-label-gmail-99',
    textClass: 'text-label-on-gmail-99 dark:text-dark-label-on-gmail-99',
    dotClass: 'bg-label-gmail-99 dark:bg-dark-label-gmail-99',
    gmailBackground: '#094228',
    gmailText: '#ffffff',
  },
  {
    id: 'deep-emerald-4',
    name: 'Deep Emerald 4',
    backgroundClass: 'bg-label-gmail-100 dark:bg-dark-label-gmail-100',
    textClass: 'text-label-on-gmail-100 dark:text-dark-label-on-gmail-100',
    dotClass: 'bg-label-gmail-100 dark:bg-dark-label-gmail-100',
    gmailBackground: '#42d692',
    gmailText: '#000000',
  },
  {
    id: 'deep-emerald-5',
    name: 'Deep Emerald 5',
    backgroundClass: 'bg-label-gmail-101 dark:bg-dark-label-gmail-101',
    textClass: 'text-label-on-gmail-101 dark:text-dark-label-on-gmail-101',
    dotClass: 'bg-label-gmail-101 dark:bg-dark-label-gmail-101',
    gmailBackground: '#16a765',
    gmailText: '#ffffff',
  },
];
export const LABEL_COLOR_BY_ID: Record<string, LabelColorSwatch> = Object.fromEntries(
  LABEL_COLOR_PALETTE.map((swatch) => [swatch.id, swatch]),
) as Record<string, LabelColorSwatch>;
export const LABEL_COLOR_BY_GMAIL_HEX: Record<string, LabelColorSwatch> = Object.fromEntries(
  LABEL_COLOR_PALETTE.map((swatch) => [
    swatch.gmailBackground.toLowerCase() + '|' + swatch.gmailText.toLowerCase(),
    swatch,
  ]),
);
export function resolveLabelColorSwatch(
  color: { background: string; text: string } | null | undefined,
): LabelColorSwatch | null {
  if (!color) return null;
  return (
    LABEL_COLOR_BY_GMAIL_HEX[color.background.toLowerCase() + '|' + color.text.toLowerCase()] ??
    null
  );
}
