[alias]
gm-test-integration = "nextest run --features test-utils --no-default-features --test integration"
gm-llvm-cov = "llvm-cov nextest --no-clean --features test-utils --no-default-features --test integration --fail-under-lines 90 --fail-under-functions 90 --fail-under-regions 80"
